id: DFFFEEBFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-05T06:53:57+00:00'
last_modified: '2022-05-26T12:16:42.081759+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    054e:
      image_group_id: I1PD95882
      title: གོས་སྔོན་པོ་ཅན་གྱི་དངོས་གྲུབ་ཉེ་བ།
      total_pages: 1379
      order: 37
      base_file: 054e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
