id: P0686D6AC
initial_creation_type: ocr
source_metadata:
  volumes:
    fbf1a6caea4e4df79cadc7b20607f43d:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: གོས་སྔོན་པོ་ཅན་གྱི་དངོས་གྲུབ་ཉེ་བ།
      total_pages: 1379
      volume_number: 37
